# Generated by Django 5.1.7 on 2025-03-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_experience_doctor_phone_alter_doctor_name_and_more'),
        ('mappings', '0001_initial'),
        ('patients', '0003_remove_patient_disease_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientDoctor',
        ),
    ]
