# Generated by Django 5.1.7 on 2025-03-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_experience_doctor_phone_alter_doctor_name_and_more'),
        ('mappings', '0002_patientdoctormapping_delete_patientdoctor'),
        ('patients', '0003_remove_patient_disease_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
